// <auto-generated />
namespace HTTP_5212_Passion_Project_RX_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class drugs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drugs));
        
        string IMigrationMetadata.Id
        {
            get { return "202202100330554_drugs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
